const merchList = [
    {
        item: '00',
        type: 'T-Shirt',
        base: 'Loreweaver',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/loreweaver-tee-2',
    },
    {
        item: '01',
        type: 'T-Shirt',
        base: 'Deathtor',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/deathtor-tee',
    },
    {
        item: '02',
        type: 'Long Sleeve',
        base: 'Loreweaver',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/loreweaver-long-sleeve',
    },
    {
        item: '03',
        type: 'Long Sleeve',
        base: 'Deathtor',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/deathtor-long-sleeve',
    },
    {
        item: '04',
        type: 'Jacket',
        base: 'Embroided Loreweaver',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/loreweaver-embroidered-jacket',
    },
    {
        item: '05',
        type: 'Hoodie',
        base: 'Loreweaver',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/loreweaver-hoodie',
    },
    {
        item: '06',
        type: 'Hoodie',
        base: 'Deathtor',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/deathtor-hoodie',
    },
    {
        item: '07',
        type: 'Zip Up Windbreaker',
        base: 'Deathtor',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/deathtor-zip-up-windbreaker',
    },
    {
        item: '08',
        type: 'Embroidered Windbreaker',
        base: 'Loreweaver',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/loreweaver-embroidered-windbreaker',
    },
    {
        item: '09',
        type: 'Bomber Jacket',
        base: 'Loreweaver',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/loreweaver-bomber-jacket',
    },
    {
        item: '10',
        type: 'Dad Hat',
        base: 'Loreweaver',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/loreweaver-dad-hat',
    },
    {
        item: '11',
        type: 'Beanie',
        base: 'Deathtor',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/deathtor-beanie',
    },
    {
        item: '12',
        type: 'Joggers',
        base: 'Deathtor',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/deathtor-joggers',
    },
    {
        item: '13',
        type: 'Basketball Shorts',
        base: 'Deathtor',
        collection: '2024',
        link: 'https://blakelw-shop.fourthwall.com/products/deathtor-basketball-shorts',
    },
]

export default merchList;